import { Children, cloneElement, useEffect, useId, useMemo, useRef, useState } from 'react'
import { supabase } from '../lib/supabaseClient'
import Icon from '../dashboard/Icon'
import { formatMoney } from '../dashboard/calc'
import Modal from '../ui/Modal'
import { useDirtyGuard, useNavGuard } from '../nav/NavGuard'
import { carTotals, itemPayload, orderPayload, orderSummary, snapshot, todayLocal, validAmount, validateCar, validateOrder } from './orderCalc'
import '../dashboard/Dashboard.css'
import '../ui/ui.css'
import './Editor.css'

const EMPTY_CAR = { brand_id: '', series_name: '', car_name: '', quantity: '1', cost_price: '', selling_price: '' }
const REDIRECT_SECONDS = 3
let keySeq = 0
const nextKey = () => `car${++keySeq}`

function CarFront() {
  return (
    <svg viewBox="0 0 120 70" width="120" height="70" aria-hidden="true">
      <ellipse cx="60" cy="62" rx="46" ry="6" fill="rgba(120,150,210,0.14)" />
      <path d="M22 44 28 24c1.5-4 4-6 8-6h48c4 0 6.5 2 8 6l6 20" fill="rgba(110,130,165,0.55)" stroke="rgba(190,205,235,0.7)" strokeWidth="1.6" strokeLinejoin="round" />
      <rect x="14" y="40" width="92" height="16" rx="6" fill="rgba(90,108,140,0.8)" stroke="rgba(190,205,235,0.6)" strokeWidth="1.6" />
      <rect x="40" y="46" width="40" height="6" rx="2" fill="rgba(30,40,60,0.8)" />
      <circle cx="26" cy="47" r="4" fill="rgba(220,230,250,0.85)" /><circle cx="94" cy="47" r="4" fill="rgba(220,230,250,0.85)" />
    </svg>
  )
}

function SuccessMark() {
  return (
    <svg viewBox="0 0 140 140" width="120" height="120" aria-hidden="true" className="ed-success-mark">
      <circle cx="70" cy="70" r="50" fill="#d6f2e0" />
      <circle cx="70" cy="70" r="34" fill="#12a150" />
      <path d="m53 71 12 12 23-26" fill="none" stroke="#fff" strokeWidth="7" strokeLinecap="round" strokeLinejoin="round" />
      <g stroke="#12a150" strokeWidth="5" strokeLinecap="round">
        <path d="M70 6v10M70 124v10M6 70h10M124 70h10M24 24l7 7M109 109l7 7M116 24l-7 7M31 109l-7 7" />
      </g>
    </svg>
  )
}

// Label + control + error text. The single child control gets the id / aria wiring.
function Field({ label, hint, error, children, className = '' }) {
  const id = useId()
  const errId = `${id}-err`
  const control = cloneElement(Children.only(children), { id, 'aria-invalid': error ? true : undefined, 'aria-describedby': error ? errId : undefined })
  return (
    <div className={`ui-field ${className}`}>
      <label className="ui-label" htmlFor={id}>{label}{hint && <> <small>{hint}</small></>}</label>
      {control}
      {error && <p className="ui-error" id={errId}>{error}</p>}
    </div>
  )
}

// New Order / Edit Order page (same layout): order details + cars. Nothing is written to the
// database until "Save Order Details"; the order number is generated by the database.
export default function NewOrder({ lookups, mode = 'new', orderId, onClose }) {
  const { sources, brands, states } = lookups
  const { requestLeave } = useNavGuard()
  const isEdit = mode === 'edit'

  const [order, setOrder] = useState(() => ({
    order_date: todayLocal(),
    source_id: sources[0] ? String(sources[0].id) : '',
    source_other: '',
    state_id: String(states.find((s) => s.name === 'West Bengal')?.id ?? ''),
    customer_type: 'new',
    shipping_paid_by_customer: '0',
    shipping_paid_by_me: '0',
    tracking_id: '',
    shipping_status: 'need_to_ship',
  }))
  const [cars, setCars] = useState([])
  const [form, setForm] = useState(null) // null | { mode: 'add' | 'edit', key?, values, errors }
  const [seriesOptions, setSeriesOptions] = useState([])
  const [status, setStatus] = useState(isEdit ? 'loading' : 'ready') // loading | ready | saving | saved | deleted | missing
  const [orderNumber, setOrderNumber] = useState('')
  const [original, setOriginal] = useState(null) // edit mode: what was loaded (to detect changes / sync cars)
  const [orderErrors, setOrderErrors] = useState({})
  const [barError, setBarError] = useState('')
  const [popup, setPopup] = useState(null) // 'saved' | 'delete'
  const [secondsLeft, setSecondsLeft] = useState(REDIRECT_SECONDS)
  const loadedFor = useRef(null)

  const brandName = (id) => brands.find((b) => String(b.id) === String(id))?.name ?? '—'
  const source = sources.find((s) => String(s.id) === String(order.source_id))
  const summary = useMemo(
    // an invalid shipping amount (negative / not a number) counts as 0 until it is corrected
    () => orderSummary(
      cars,
      validAmount(order.shipping_paid_by_customer) ? order.shipping_paid_by_customer : 0,
      validAmount(order.shipping_paid_by_me) ? order.shipping_paid_by_me : 0,
    ),
    [cars, order.shipping_paid_by_customer, order.shipping_paid_by_me],
  )

  // Series suggestions from cars already recorded (read-only convenience; typing a new series is fine).
  useEffect(() => {
    let cancelled = false
    supabase.from('order_items').select('series_name').limit(1000).then(({ data }) => {
      if (!cancelled && data) setSeriesOptions([...new Set(data.map((r) => r.series_name).filter(Boolean))].sort())
    })
    return () => { cancelled = true }
  }, [])

  async function loadOrder() {
    const [o, it] = await Promise.all([
      supabase.from('orders').select('*').eq('id', orderId).single(),
      supabase.from('order_items').select('id,brand_id,series_name,car_name,quantity,cost_price,selling_price').eq('order_id', orderId).order('created_at'),
    ])
    if (o.error || !o.data) { setStatus('missing'); return }
    const loaded = {
      order_date: o.data.order_date, source_id: String(o.data.source_id), source_other: o.data.source_other || '',
      state_id: String(o.data.state_id), customer_type: o.data.customer_type,
      shipping_paid_by_customer: String(o.data.shipping_paid_by_customer ?? 0), shipping_paid_by_me: String(o.data.shipping_paid_by_me ?? 0),
      tracking_id: o.data.tracking_id || '', shipping_status: o.data.shipping_status,
    }
    const loadedCars = (it.data || []).map((c) => ({
      key: nextKey(), id: c.id, brand_id: String(c.brand_id), series_name: c.series_name, car_name: c.car_name,
      quantity: String(c.quantity), cost_price: String(c.cost_price), selling_price: String(c.selling_price),
    }))
    setOrder(loaded); setOrderNumber(o.data.order_number); setCars(loadedCars); setForm(null)
    setOriginal({ snap: snapshot(loaded, loadedCars, sources), carsById: Object.fromEntries(loadedCars.map((c) => [c.id, JSON.stringify(itemPayload(c))])) })
    setStatus('ready')
  }

  useEffect(() => {
    if (!isEdit || loadedFor.current === orderId) return
    loadedFor.current = orderId
    loadOrder()
  }, [isEdit, orderId]) // eslint-disable-line react-hooks/exhaustive-deps

  // Unsaved changes: New Order = at least one car submitted; Edit = anything differs from what was loaded.
  const dirty = !!form || (isEdit ? original !== null && snapshot(order, cars, sources) !== original.snap : cars.length > 0)
  useDirtyGuard(dirty && status !== 'saved' && status !== 'deleted')

  // After a successful save: count down, then return to the Sales landing page on its own.
  useEffect(() => {
    if (popup !== 'saved') return undefined
    const id = setInterval(() => setSecondsLeft((n) => n - 1), 1000)
    return () => clearInterval(id)
  }, [popup])
  useEffect(() => { if (popup === 'saved' && secondsLeft <= 0) onClose() }, [popup, secondsLeft, onClose])

  const setField = (k, v) => { setOrder((o) => ({ ...o, [k]: v })); setOrderErrors((e) => ({ ...e, [k]: undefined })); setBarError('') }

  // ---- cars -----------------------------------------------------------------------------
  const openAdd = () => setForm({ mode: 'add', values: { ...EMPTY_CAR }, errors: {} })
  const openEdit = (c) => setForm({
    mode: 'edit', key: c.key, errors: {},
    values: { brand_id: c.brand_id, series_name: c.series_name, car_name: c.car_name, quantity: c.quantity, cost_price: c.cost_price, selling_price: c.selling_price },
  })
  const setCarField = (k, v) => setForm((f) => ({ ...f, values: { ...f.values, [k]: v }, errors: { ...f.errors, [k]: undefined } }))

  function submitCar(e) {
    e.preventDefault()
    const errors = validateCar(form.values)
    if (Object.keys(errors).length) { setForm((f) => ({ ...f, errors })); return } // invalid: stay on the form
    if (form.mode === 'add') setCars((cs) => [...cs, { key: nextKey(), ...form.values }])
    else setCars((cs) => cs.map((c) => (c.key === form.key ? { ...c, ...form.values } : c)))
    setForm(null)
    setBarError('')
  }
  const deleteCar = (key) => setCars((cs) => cs.filter((c) => c.key !== key)) // no confirmation

  async function save() {
    setBarError('')
    if (form) { setBarError('Submit or cancel the car details before saving.'); return }
    if (cars.length === 0) return
    const errors = validateOrder(order, sources)
    if (Object.keys(errors).length) { setOrderErrors(errors); setBarError('Please fix the highlighted order details.'); return }

    setStatus('saving')
    const payload = orderPayload(order, sources)

    if (!isEdit) {
      // 1) the order (the database generates the permanent order number from the order date)
      const { data: created, error } = await supabase.from('orders').insert(payload).select('id,order_number').single()
      if (error) { setStatus('ready'); setBarError(error.message); return }
      // 2) all its cars
      const { error: itemError } = await supabase.from('order_items').insert(cars.map((c) => ({ order_id: created.id, ...itemPayload(c) })))
      if (itemError) {
        await supabase.from('orders').delete().eq('id', created.id) // never leave a car-less order behind
        setStatus('ready'); setBarError(itemError.message); return
      }
      setOrderNumber(created.order_number)
    } else {
      const fail = async (message) => { setBarError(message); await loadOrder() } // show the error and re-sync with the database
      const { error } = await supabase.from('orders').update(payload).eq('id', orderId)
      if (error) { await fail(error.message); return }
      const keepIds = new Set(cars.filter((c) => c.id).map((c) => c.id))
      const removed = Object.keys(original.carsById).filter((id) => !keepIds.has(id))
      if (removed.length) {
        const { error: delError } = await supabase.from('order_items').delete().in('id', removed)
        if (delError) { await fail(delError.message); return }
      }
      for (const c of cars.filter((x) => x.id && JSON.stringify(itemPayload(x)) !== original.carsById[x.id])) {
        const { error: upError } = await supabase.from('order_items').update(itemPayload(c)).eq('id', c.id)
        if (upError) { await fail(upError.message); return }
      }
      const added = cars.filter((c) => !c.id)
      if (added.length) {
        const { error: addError } = await supabase.from('order_items').insert(added.map((c) => ({ order_id: orderId, ...itemPayload(c) })))
        if (addError) { await fail(addError.message); return }
      }
    }
    setSecondsLeft(REDIRECT_SECONDS)
    setStatus('saved')
    setPopup('saved')
  }

  // Permanently removes the order; its cars go with it (ON DELETE CASCADE). The order number is never reused
  // because the database counter only ever goes up.
  async function confirmDelete() {
    const { error } = await supabase.from('orders').delete().eq('id', orderId)
    setPopup(null)
    if (error) { setBarError(error.message); return }
    setStatus('deleted')
    onClose()
  }

  const leave = () => requestLeave(onClose) // asks first when there are unsaved changes

  const f = form?.values
  const fe = form?.errors || {}
  const shipCError = orderErrors.shipping_paid_by_customer || (validAmount(order.shipping_paid_by_customer) ? undefined : 'Enter a valid amount')
  const shipMeError = orderErrors.shipping_paid_by_me || (validAmount(order.shipping_paid_by_me) ? undefined : 'Enter a valid amount')
  const saving = status === 'saving'

  if (status === 'loading') return <div className="db ed-root"><div className="db-card db-message">Loading order…</div></div>
  if (status === 'missing') {
    return (
      <div className="db ed-root">
        <div className="db-card db-message" role="alert">This order could not be found. <button type="button" className="ui-btn outline sm" onClick={onClose}>Back to Orders</button></div>
      </div>
    )
  }

  const cards = [
    { label: 'Total Cars', value: String(summary.cars), icon: 'car', tone: 'blue' },
    { label: 'Total Cost Price', value: formatMoney(summary.cost), icon: 'coins', tone: 'amber' },
    { label: 'Total Selling Price', value: formatMoney(summary.sell), icon: 'tag', tone: 'red' },
    { label: 'Gross Profit', value: formatMoney(summary.gross), pct: `(${summary.grossPct.toFixed(2)}%)`, icon: 'bars', tone: 'purple' },
    { label: 'Shipping by Customer', value: formatMoney(summary.shipC), icon: 'truck', tone: 'green' },
    { label: 'Shipping by Me', value: formatMoney(summary.shipMe), icon: 'truck', tone: 'blue' },
  ]

  return (
    <div className="db ed-root">
      <header className="ed-header">
        <div>
          <h2 className="ed-title">{isEdit ? 'Edit Order' : 'New Order'}</h2>
          <p className="ed-subtitle">{isEdit ? 'Update order details and modify the cars in this order.' : 'Enter order details and add the cars in this order.'}</p>
        </div>
        <div className="ed-header-actions">
          <button type="button" className="ui-btn outline" onClick={leave}><Icon name="arrowLeft" size={20} />Back to Orders</button>
          {isEdit && <button type="button" className="ui-btn outline-red" onClick={() => setPopup('delete')}><Icon name="trash" size={20} />Delete Order</button>}
        </div>
      </header>

      <section className="db-card ed-card">
        <div className="ed-card-head">
          <h3 className="ed-card-title"><Icon name="doc" size={24} />Order Details</h3>
          {!isEdit && <span className="ed-note">Order number is generated when saved.</span>}
        </div>
        <div className="ed-grid">
          {isEdit && (
            <Field label="Order number"><input className="ui-control" value={orderNumber} disabled readOnly /></Field>
          )}
          <Field label="Order date" error={orderErrors.order_date}>
            <input type="date" className={`ui-control${orderErrors.order_date ? ' invalid' : ''}`} value={order.order_date} onChange={(e) => setField('order_date', e.target.value)} />
          </Field>
          <Field label="Source" error={orderErrors.source_id}>
            <select className="ui-control" value={order.source_id} onChange={(e) => setField('source_id', e.target.value)}>
              {sources.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </Field>
          <Field label="State" error={orderErrors.state_id}>
            <select className="ui-control" value={order.state_id} onChange={(e) => setField('state_id', e.target.value)}>
              {states.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </Field>
          <Field label="Customer">
            <select className="ui-control" value={order.customer_type} onChange={(e) => setField('customer_type', e.target.value)}>
              <option value="new">New customer</option>
              <option value="existing">Existing customer</option>
            </select>
          </Field>
          <Field label="Shipping paid by customer (₹)" error={shipCError}>
            <input type="number" min="0" step="0.01" className={`ui-control${shipCError ? ' invalid' : ''}`} value={order.shipping_paid_by_customer} onChange={(e) => setField('shipping_paid_by_customer', e.target.value.replace(/^0+(?=\d)/, ''))} />
          </Field>
          <Field label="Shipping paid by me (₹)" error={shipMeError}>
            <input type="number" min="0" step="0.01" className={`ui-control${shipMeError ? ' invalid' : ''}`} value={order.shipping_paid_by_me} onChange={(e) => setField('shipping_paid_by_me', e.target.value.replace(/^0+(?=\d)/, ''))} />
          </Field>
          <Field label="Tracking ID" hint="(optional)">
            <input className="ui-control" placeholder="e.g. AWB123456" value={order.tracking_id} onChange={(e) => setField('tracking_id', e.target.value)} />
          </Field>
          <Field label="Shipping status">
            <select className="ui-control" value={order.shipping_status} onChange={(e) => setField('shipping_status', e.target.value)}>
              <option value="need_to_ship">Need To Ship</option>
              <option value="shipped">Shipped</option>
              <option value="delivered">Delivered</option>
            </select>
          </Field>
          {source?.requires_detail && (
            <Field label="Exact source" error={orderErrors.source_other} className="ed-span2">
              <input className={`ui-control${orderErrors.source_other ? ' invalid' : ''}`} placeholder="e.g. a specific Facebook group" value={order.source_other} onChange={(e) => setField('source_other', e.target.value)} />
            </Field>
          )}
        </div>
      </section>

      <div className="ed-summary">
        {cards.map((c) => (
          <div key={c.label} className="db-card db-kpi">
            <div className="db-kpi-body">
              <span className={`db-kpi-icon tone-${c.tone}`}><Icon name={c.icon} size={24} /></span>
              <div className="db-kpi-label">{c.label}</div>
              <div className={`db-kpi-value${c.value.length > 10 ? ' long' : ''}`}>{c.value}{c.pct && <span className="sl-pct"> {c.pct}</span>}</div>
            </div>
          </div>
        ))}
      </div>

      <section className="db-card ed-card">
        <div className="ed-card-head">
          <h3 className="ed-card-title"><Icon name="list" size={24} />Cars in this order</h3>
          <span className="ed-count">{summary.cars} car{summary.cars === 1 ? '' : 's'}</span>
        </div>

        {cars.length === 0 && !form && (
          <div className="ed-empty">
            <CarFront />
            <p className="ed-empty-title">No cars added yet.</p>
            <p className="ed-empty-sub">Click the button below to add the first car to this order.</p>
            <button type="button" className="ui-btn red" onClick={openAdd}><Icon name="plus" size={20} />Add Car Details</button>
          </div>
        )}

        {cars.length > 0 && (
          <div className="ed-table-wrap">
            <table className="ed-table">
              <thead>
                <tr><th>#</th><th>Brand</th><th>Series</th><th>Car name</th><th>Qty</th><th>Total CP (₹)</th><th>Total SP (₹)</th><th className="c">Action</th></tr>
              </thead>
              <tbody>
                {cars.map((c, i) => {
                  const t = carTotals(c)
                  return (
                    <tr key={c.key}>
                      <td>{i + 1}</td>
                      <td>{brandName(c.brand_id)}</td>
                      <td>{c.series_name}</td>
                      <td>{c.car_name}</td>
                      <td>{c.quantity}</td>
                      <td>{formatMoney(t.cp)}</td>
                      <td>{formatMoney(t.sp)}</td>
                      <td className="c">
                        <span className="ed-row-actions">
                          <button type="button" className="ui-btn outline-blue sm" disabled={!!form} aria-label={`Edit car ${i + 1}`} onClick={() => openEdit(c)}><Icon name="pencil" size={18} />Edit</button>
                          <button type="button" className="ui-btn outline-red sm" disabled={!!form} aria-label={`Delete car ${i + 1}`} onClick={() => deleteCar(c.key)}><Icon name="trash" size={18} />Delete</button>
                        </span>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}

        {form && (
          <form className="ed-carform" onSubmit={submitCar} noValidate>
            <h4 className="ed-carform-title">{form.mode === 'add' ? 'Add Car Details' : 'Edit Car Details'}</h4>
            <div className="ed-carform-grid">
              <Field label="Brand" error={fe.brand_id}>
                <select className={`ui-control${fe.brand_id ? ' invalid' : ''}`} value={f.brand_id} onChange={(e) => setCarField('brand_id', e.target.value)}>
                  <option value="">Select brand</option>
                  {brands.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}
                </select>
              </Field>
              <Field label="Series" error={fe.series_name}>
                <input className={`ui-control${fe.series_name ? ' invalid' : ''}`} list="ed-series" placeholder="e.g. Mainline" value={f.series_name} onChange={(e) => setCarField('series_name', e.target.value)} />
              </Field>
              <Field label="Car name" error={fe.car_name}>
                <input className={`ui-control${fe.car_name ? ' invalid' : ''}`} value={f.car_name} onChange={(e) => setCarField('car_name', e.target.value)} />
              </Field>
              <Field label="Qty" error={fe.quantity}>
                <input type="number" min="1" step="1" className={`ui-control${fe.quantity ? ' invalid' : ''}`} value={f.quantity} onChange={(e) => setCarField('quantity', e.target.value)} />
              </Field>
              <Field label="CP / car (₹)" error={fe.cost_price}>
                <input type="number" min="0" step="0.01" className={`ui-control${fe.cost_price ? ' invalid' : ''}`} value={f.cost_price} onChange={(e) => setCarField('cost_price', e.target.value)} />
              </Field>
              <Field label="SP / car (₹)" error={fe.selling_price}>
                <input type="number" min="0" step="0.01" className={`ui-control${fe.selling_price ? ' invalid' : ''}`} value={f.selling_price} onChange={(e) => setCarField('selling_price', e.target.value)} />
              </Field>
              <datalist id="ed-series">{seriesOptions.map((s) => <option key={s} value={s} />)}</datalist>
              <div className="ed-carform-actions">
                <button type="submit" className="ui-btn green">{form.mode === 'add' ? 'Submit' : 'Update'}</button>
                <button type="button" className="ui-btn outline" onClick={() => setForm(null)}>Cancel</button>
              </div>
            </div>
          </form>
        )}

        {(cars.length > 0 || form) && (
          <div className="ed-addrow">
            <button type="button" className="ui-btn red" disabled={!!form} onClick={openAdd}><Icon name="plus" size={20} />Add Car Details</button>
            {form && <p className="ed-hint"><Icon name="info" size={18} />Complete the car details above or cancel to add more cars.</p>}
          </div>
        )}
      </section>

      <section className="db-card ed-bar">
        {barError
          ? <p className="ed-barmsg err" role="alert"><Icon name="info" size={22} />{barError}</p>
          : cars.length === 0
            ? <p className="ed-barmsg err"><Icon name="info" size={22} />Please add at least one car to this order before saving.</p>
            : <span />}
        <div className="ed-bar-actions">
          <button type="button" className="ui-btn outline" onClick={leave}>Cancel</button>
          <button type="button" className="ui-btn red" disabled={cars.length === 0 || saving} onClick={save}>
            <Icon name="save" size={20} />{saving ? 'Saving…' : 'Save Order Details'}
          </button>
        </div>
      </section>

      {popup === 'saved' && (
        <Modal variant="light" title={isEdit ? 'Successfully Edited your Order' : 'Successfully Added your Order'}>
          <SuccessMark />
          <p className="ui-modal-text">{isEdit
            ? 'Your changes have been saved successfully.\nRedirecting to Sales page in a few seconds…'
            : 'Your order has been saved successfully.\nRedirecting to Sales page in a few seconds…'}</p>
          <div className="ui-progress"><span style={{ width: `${Math.min(100, ((REDIRECT_SECONDS - secondsLeft + 1) / REDIRECT_SECONDS) * 100)}%` }} /></div>
          <p className="ui-countdown">Redirecting in {Math.max(secondsLeft, 1)} second{secondsLeft === 1 ? '' : 's'}…</p>
        </Modal>
      )}

      {popup === 'delete' && (
        <Modal variant="light" title="Delete Order?" onClose={() => setPopup(null)}>
          <span className="ui-modal-icon" style={{ background: '#fde7ea', color: '#e11d3a' }}><Icon name="trash" size={38} /></span>
          <p className="ui-modal-text">{`This will permanently delete ${orderNumber} and all its car entries. This action cannot be undone.`}</p>
          <p className="ui-modal-note"><Icon name="info" size={22} />This action is permanent and cannot be undone.</p>
          <div className="ui-modal-actions">
            <button type="button" className="ui-btn outline-light" onClick={() => setPopup(null)}>Cancel</button>
            <button type="button" className="ui-btn red" onClick={confirmDelete}><Icon name="trash" size={20} />Delete Order</button>
          </div>
        </Modal>
      )}
    </div>
  )
}
